api/urls.py
from django.urls import path
from .views import AllUsersAPIView, ListOfPostsAPIView, CreatePostAPIView, DeletePostAPIView, SignUpAPIView, SignInAPIView

app_name = 'api'

urlpatterns = [
    path('all_users/', AllUsersAPIView.as_view(), name='all_users'),
    path('posts_of_user/', ListOfPostsAPIView.as_view(), name='posts_of_user'),
    path('add_post/', CreatePostAPIView.as_view(), name='add_post'),
    path('delete_post/<int:id>/', DeletePostAPIView.as_view(), name='delete_post'),
    path('sign_up/', SignUpAPIView.as_view(), name='sign_up'),
    path('sign_in/', SignInAPIView.as_view(), name='sign_in'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('api/', include('api.urls', namespace='api')),
]

main/urls.py
from django.urls import path
from .views import Home, Posts

app_name = 'main'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('posts/<int:id>', Posts.as_view(), name='posts'),
]

api/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator


class MyUser(AbstractBaseUser, PermissionsMixin, models.Model):
    """ Кастомная модель пользователя. Никаких изменений за исключением отключения некоторых полей, согласно тз. """

    username_validator = UnicodeUsernameValidator()

    last_login = None
    groups = None
    user_permissions = None

    username = models.CharField(verbose_name="Имя пользователя",
                                max_length=150, unique=True, validators=[username_validator])
    email = models.EmailField(verbose_name='Email', unique=True)
    is_staff = models.BooleanField(
        verbose_name='staff status',
        default=False,
        help_text='Designates whether the user can log into this admin site.',
    )

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'

    objects = UserManager()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Post(models.Model):
    """ Модель поста """

    user = models.ForeignKey(
        MyUser, on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(verbose_name='Заголовок поста', max_length=128)
    body = models.TextField(verbose_name='Текст поста')

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.title

api/views.py
from rest_framework.response import Response
from rest_framework.request import Request
from rest_framework.generics import ListAPIView, CreateAPIView, DestroyAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView

from .serializers import ListOfUserSerializer, ListOfUserPostsSerializer, AddPostSerializer, SignUpSerializer, SignInSerializer
from main.models import MyUser, Post

from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse


class AllUsersAPIView(ListAPIView):
    """ View для отображения всех пользователей в системе """

    serializer_class = ListOfUserSerializer
    queryset = MyUser.objects.all()


class ListOfPostsAPIView(ListAPIView):
    """ View для отображения всех постов пользователя """

    serializer_class = ListOfUserPostsSerializer
    queryset = Post.objects.none()

    def get(self, request, *args, **kwargs):
        self.queryset = Post.objects.filter(user=self.request.user)
        return super().get(request, *args, **kwargs)


class CreatePostAPIView(CreateAPIView):
    """ View для создания поста """

    serializer_class = AddPostSerializer
    permission_classes = (IsAuthenticated, )

    def post(self, request: Request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(user=self.request.user)
        return Response(status=201)


class DeletePostAPIView(DestroyAPIView):
    """ View для удаления поста """

    permission_classes = (IsAuthenticated, )
    lookup_field = 'id'
    queryset = Post.objects.none()

    def destroy(self, request: Request, *args, **kwargs):
        self.queryset = Post.objects.filter(user=request.user)
        return super().destroy(request, *args, **kwargs)


class SignUpAPIView(CreateAPIView):
    """ View для обработки регистрации """
    serializer_class = SignUpSerializer
    queryset = MyUser.objects.none()

    def get(self, request: Request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('main:home'))
        return Response(status=405)

    def post(self, request: Request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        MyUser.objects.create_user(
            username=serializer.validated_data.get('username'),
            email=serializer.validated_data.get('email'),
            password=serializer.validated_data.get('password'))

        user = authenticate(request, username=serializer.validated_data.get(
            'username'), password=serializer.validated_data.get('password'))
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('main:home'))
        return Response(status=401)


class SignInAPIView(APIView):
    """ View для обработки авторизации """

    def post(self, request: Request, *args, **kwargs):
        serializer = SignInSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = authenticate(request, username=serializer.validated_data.get(
            'username'), password=serializer.validated_data.get('password'))
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('main:home'))
        return Response(status=401)

    def get(self, request: Request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('main:home'))
        return Response(status=405)

main/views.py
from typing import Any, Dict
from django.http import HttpRequest, HttpResponse
from django.views.generic import TemplateView
from .models import MyUser, Post

class Home(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['users'] = MyUser.objects.all()
        return context

class Posts(TemplateView):
    template_name = 'posts.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        return context
    
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        context = self.get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(user__id = kwargs.get('id'))
        context['author'] = MyUser.objects.filter(id = kwargs.get('id')).first()
        return self.render_to_response(context)

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <div class="main">
        <div class="users">
            {% for user in users %}
                <div class="user">
                    <h1>
                        <a href="posts/{{ user.id }}">{{ user.username }}</a>
                    </h1>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

templates/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Posts</title>
</head>
<body>
    <div class="main">
        {% csrf_token %}
        <div class="posts">
            {% for post in posts %}
                <div class="post">
                    <h1>{{ post.title }}</h1>
                    <p>{{ post.body }}</p>
                    <h3>автор - {{ post.user.username }}</h3>
                </div>
                {% if request.user == author %}
                    <div class="form">
                        <div class="delete_new_post_form">
                            <form post-id="{{ post.id }}" class="delete_form">
                                <button style="color: red; padding:10px 15px" type="submit">Удалить</button>
                            </form>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            {% if request.user == author %}
                <div style="margin-top: 20px;" class="add_new_post_form">
                    <form style="display: flex; flex-direction:column; gap: 15px; max-width: 30%;">
                        <input type="text" name="title" placeholder="Заголовок поста">
                        <textarea name="body" placeholder="Содержимое поста" cols="30" rows="10"></textarea>
                        <button style="color: rgb(0, 102, 255); padding:10px 15px" type="submit">Добавить</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
    <script>
        const delete_forms = document.querySelectorAll('form.delete_form')
        delete_forms.forEach(form => {
            form.addEventListener('submit', e => {
                e.preventDefault()
                fetch(`/api/delete_post/${form.getAttribute('post-id')}/`, {
                    method: 'DELETE',
                    headers: {
                        'X-CSRFToken': document.querySelector('input[name=csrfmiddlewaretoken]').value,
                    }
                }).then(response => {
                    if(response.status == 204){
                        window.location.reload()
                    }
                })
            })
        })
        const add_new_post_form = document.querySelector('.add_new_post_form form')
        add_new_post_form.addEventListener('submit', e => {
            e.preventDefault()
                fetch("{% url 'api:add_post' %}", {
                    method: 'POST',
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'application/json;charset=utf-8',
                        'X-CSRFToken': document.querySelector('input[name=csrfmiddlewaretoken]').value,
                    },
                    body: JSON.stringify({
                        title: add_new_post_form.querySelector('input[name="title"]').value,
                        body: add_new_post_form.querySelector('textarea[name="body"]').value,
                    })
                }).then(response => {
                    if(response.status == 201){
                        window.location.reload()
                    }
                })
        })
    </script>
</body>
</html>